robot:
  algorithmPluginDir: "plugin"
exchanges:
  zaif:
    keys:
    - key: "key"
      secret: "secret"
    currencyPairs:
    - btc_jpy
    - xem_jpy
    - mona_jpy
    - bch_jpy
    - eth_jpy
    - zaif_jpy
    - pepecash_jpy
    - xem_btc
    - mona_btc
    - bch_btc
    - eth_btc
    - zaif_btc
    - pepecash_btc
    retry: 0
    retryWait: 0
    timeout: 0
    readBufSize: 0
    writeBufSize: 0
    BindAddresses:
      - 127.0.0.1
    proxysAddrPort:
      127.0.0.1:28888:
      - btc_jpy
      - xem_jpy
      - mona_jpy
      - bch_jpy
      - eth_jpy
      - zaif_jpy
      - pepecash_jpy
      - xem_btc
      - mona_btc
      - bch_btc
      - eth_btc
      - zaif_btc
      - pepecash_btc
  coincheck:
    apikey: "key"
    apisecret: "secret"
server:
  debug: true
  addrPort: 127.0.0.1:38080
notifier:
  mail:
    hostPort:
    username:
    password:
    authType:
    useTls:
    useStartTls:
    from:
    to:
  ifttt:
    key: "webhook-key"
logger:
  output: "stdout"
