currencyPairs:
  - btc_jpy
  - xem_jpy
  - mona_jpy
  - bch_jpy
  - eth_jpy
  - zaif_jpy
  - pepecash_jpy
  - xem_btc
  - mona_btc
  - bch_btc
  - eth_btc
  - zaif_btc
  - pepecash_btc
retry: 0
retryWait: 19
timeout: 0
clientBindAddresses:
- 127.0.0.1
- 127.0.0.2
- 127.0.0.3
- 127.0.0.4
- 127.0.0.5
readBufSize: 0
writeBufSize: 0
pollingWait: 34
pauseWait: 60
server:
  addrPort: 127.0.0.1:28888
logger:
  output: "stdout"
